name: Trakt → YAML Sync

on:
  schedule:
    - cron: "17 1 * * *" # UTC
  workflow_dispatch:

concurrency:
  group: trakt-sync
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml pynacl   # ← PyNaCl für Secret-Rotation
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Run Trakt enrichment + sync
        env:
          TRAKT_CLIENT_ID:     ${{ secrets.TRAKT_CLIENT_ID }}
          TRAKT_CLIENT_SECRET: ${{ secrets.TRAKT_CLIENT_SECRET }}
          TRAKT_ACCESS_TOKEN:  ${{ secrets.TRAKT_ACCESS_TOKEN }}
          TRAKT_REFRESH_TOKEN: ${{ secrets.TRAKT_REFRESH_TOKEN }}
          TRAKT_USERNAME:      ${{ secrets.TRAKT_USERNAME }}
          TMDB_API_KEY:        ${{ secrets.TMDB_API_KEY }}
          GH_PAT:              ${{ secrets.GH_PAT }}                # ← wichtig
          GITHUB_REPOSITORY:   ${{ github.repository }}             # ← für API
          OUTPUT_DIR: _data
        run: |
          python scripts/trakt_sync.py

      - name: Commit & push changes
        run: |
          set -e
          git config user.name  "trakt-sync-bot"
          git config user.email "actions@users.noreply.github.com"
          git add _data/watched_movies.yml _data/watched_episodes.yml || true
          if git diff --cached --quiet; then
            echo "No content changes to commit."
          else
            git commit -m "chore(trakt): update enrichment + watched lists"
            git push
          fi
