name: Trakt → YAML Sync

on:
  schedule:
    # Achtung: UTC! 01:17 UTC ≈ 03:17 Europe/Berlin (Sommerzeit)
    - cron: "17 1 * * *"
  workflow_dispatch:

# verhindert parallele Läufe (die sonst Tokens gegenseitig invalidieren)
concurrency:
  group: trakt-sync
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
          sudo apt-get update -y
          sudo apt-get install -y jq
          if ! command -v gh >/dev/null 2>&1; then
            sudo apt-get install -y gh
          fi
          gh --version

      - name: Run Trakt sync
        env:
          TRAKT_CLIENT_ID:     ${{ secrets.TRAKT_CLIENT_ID }}
          TRAKT_CLIENT_SECRET: ${{ secrets.TRAKT_CLIENT_SECRET }}
          TRAKT_ACCESS_TOKEN:  ${{ secrets.TRAKT_ACCESS_TOKEN }}   # optional
          TRAKT_REFRESH_TOKEN: ${{ secrets.TRAKT_REFRESH_TOKEN }}
          TMDB_API_KEY:        ${{ secrets.TMDB_API_KEY }}
          OUTPUT_DIR: _data
          TRAKT_HISTORY_LIMIT: "200"
          TRAKT_HISTORY_PAGES: "5"
        run: |
          python scripts/trakt_sync.py

      # Secret-Rotation NUR wenn neue Tokens-Datei existiert
      - name: Authenticate gh for secret rotation
        if: ${{ hashFiles('.trakt_tokens.json') != '' }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}   # PAT (classic) mit 'repo'
        run: |
          set -euo pipefail
          gh auth status || gh auth setup-git || true

      - name: Rotate Trakt refresh token secret (if updated)
        if: ${{ hashFiles('.trakt_tokens.json') != '' }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          set -euo pipefail
          if [ ! -f ".trakt_tokens.json" ]; then
            echo "No .trakt_tokens.json — skipping rotation."
            exit 0
          fi
          NEW_REFRESH="$(jq -r '.refresh_token' .trakt_tokens.json)"
          if [ -z "$NEW_REFRESH" ] || [ "$NEW_REFRESH" = "null" ]; then
            echo "No new refresh_token found — skipping."
            exit 0
          fi
          gh secret set TRAKT_REFRESH_TOKEN --repo "$GITHUB_REPOSITORY" --body "$NEW_REFRESH"
          echo "Updated TRAKT_REFRESH_TOKEN secret."

          # Optional: auch Access-Token rotieren (nicht zwingend)
          NEW_ACCESS="$(jq -r '.access_token' .trakt_tokens.json)"
          if [ -n "$NEW_ACCESS" ] && [ "$NEW_ACCESS" != "null" ]; then
            gh secret set TRAKT_ACCESS_TOKEN --repo "$GITHUB_REPOSITORY" --body "$NEW_ACCESS"
            echo "Updated TRAKT_ACCESS_TOKEN secret (optional)."
          fi

      - name: Commit & push changes (YAML, cursor)
        run: |
          set -e
          git config user.name  "trakt-sync-bot"
          git config user.email "actions@users.noreply.github.com"
          git add _data/watched_movies.yml _data/watched_episodes.yml .trakt_cursor || true
          if git diff --cached --quiet; then
            echo "No content changes to commit."
          else:
            git commit -m "chore(trakt): update history + cursor"
            git push
          fi
